### ISSUE TITLE
Register a nib file

### ISSUE THREAD

**Issue by umeshiscreative** [andrea-prearo/GenericDataSource#1]
First thanks for making this code, I am using this code but I am unable to register a nib file using this code How can I register a nib file using Generic method?

**Comment by andrea-prearo** [comment]
I didn't try to register a nib programmatically. In the code examples ([PhotoList](https://github.com/andrea-prearo/GenericDataSource/tree/master/PhotoList) and [TaskList](https://github.com/andrea-prearo/GenericDataSource/tree/master/TaskList)) I am using a storyboard to take care of that. As long as the cell identifier is the same as the cell class name everything should work as expected.

<img width="1680" alt="photolist" src="https://user-images.githubusercontent.com/12599697/39313904-fa165ecc-4927-11e8-9757-7b077dcab856.png">
<img width="1680" alt="tasklist" src="https://user-images.githubusercontent.com/12599697/39313905-fa38e046-4927-11e8-8bda-2e8e4984a30c.png">

It is possible that additional code may be required to properly handle registering a nib file. Please, feel free to submit a PR in case you come up with a working solution. Thanks!
